title: Yet another Portfolio
url: 'https://amine.tayaa.me'
baseurl: '' #change it according to your repository name



# Profile information
yourname: TAYAA Med Amine  ## put your name
title: 'Developer &amp; System Administrator'  ## your title
location: Taza, MA

summary: Passionate Self-Learner looking to promote the adoption &amp; usage of Technology in the everyday life of everyone.

## Social Profiles
facebook: https://facebook.com/tayamino  ## your facebook account url
twitter: https://twitter.com/tayamino  ## your twitter account url
linkedin: https://ma.linkedin.com/in/shivhack  ## your linkedin account url
github: https://github.com/tayamino  ## you dribbble account url
foursquare: https://foursquare.com/shivhack  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
